const shimagelist = {
    "공기밥" : require("./공기밥.png").default,
    "김치우동" : require("./김치우동.png").default,
    "꼬치어묵우동" : require("./꼬치어묵우동.png").default,
    "돈까스정식" : require("./돈까스정식.png").default,
    "돈도리볶음밥" : require("./돈도리볶음밥.png").default,
    "떡라면" : require("./떡라면.png").default,
    "떡만두국" : require("./떡만두국.png").default,
    "라면" : require("./라면.png").default,
    "Hot소세지오믈렛" : require("./Hot소세지오믈렛.png").default,
    "매운 돼지불고기" : require("./매운 돼지불고기.png").default,
    "소금구이덮밥" : require("./소금구이덮밥.png").default,
    "새우튀김 오믈렛" : require("./새우튀김 오믈렛.png").default,
    "새우튀김우동" : require("./새우튀김우동.png").default,
    "소고기버섯육개장" : require("./소고기버섯육개장.png").default,
    "야채김밥" : require("./야채김밥.png").default,
    "얼큰 순대국" : require("./얼큰순대국.png").default,
    "오믈렛" : require("./오믈렛.png").default,
    "왕양푼이비빔밥" : require("./왕양푼이비빔밥.png").default,
    "우유(우동+유부초밥)" : require("./우유(우동+유부초밥).png").default,
    "유부초밥" : require("./유부초밥.png").default,
    "자장면" : require("./자장면.png").default,
    "자장밥" : require("./자장밥.png").default,
    "중식볶음밥" : require("./중식볶음밥.png").default,
    "짬뽕" : require("./짬뽕.png").default,
    "참치마요비빔밥" : require("./참치마요비빔밥.png").default,
    "초밥&돈까스" : require("./초밥&돈까스.png").default,
    "치즈김밥" : require("./치즈김밥.png").default,
    "치즈돈까스" : require("./치즈돈까스.png").default,
    "치즈라면" : require("./치즈라면.png").default,
    "치킨까스" : require("./치킨까스.png").default,
    "치킨볼 오믈렛" : require("./치킨볼 오믈렛.png").default,
    "탕볶밥" : require("./탕볶밥.png").default,
    "왕돈까스" : require("./왕돈까스.png").default,
    "탕수육세트" : require("./탕수육세트.png").default,
};

export default shimagelist;